---
title: "STAA 566 HW1"
author: "Tuul Purevjav"
date: "1/27/2022"
output: html_document
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

My husband and I are putting our house on the market in a few months.  To get a general idea of the housing market in where I live, I located this graph at https://fred.stlouisfed.org/series/AVELISPRI49049 via Google Dataset Search. I downloaded the CVS data and tried to visualize it in a similar way.

```{r}
library(ggplot2)
library(ggthemes)
data1 <- read.csv("AVELISPRI49049.csv")
```

```{r}
p_data1 <- ggplot(data = data1, mapping = aes(x = as.Date(DATE), y = AVELISPRI49049)) +
  geom_line(color = "steelblue") +
  theme_minimal(base_size=12, base_family = "sans") +
  scale_y_log10() + scale_y_continuous(trans = "log10", 
                                        labels = scales::dollar_format(), 
                                        breaks = seq(400000, 1200000, by = 100000)) +
  scale_x_date(date_breaks = "1 year", date_labels = "%b %Y")+
  ylab("U.S. Dollars") + 
  xlab("Years")+ 
  labs(title = "Average Home Listing Price in Utah County, UT")
p_data1

```

